-- Esquema inicial de TiCo.
--
-- Generado a partir del DDL real que Hibernate produce para las entidades
-- JPA actuales usando PostgreSQLDialect (capturado con
-- jakarta.persistence.schema-generation.scripts.action=create), no escrito
-- a mano, para garantizar que coincide exactamente con lo que
-- spring.jpa.hibernate.ddl-auto=update habría creado. A partir de esta
-- migración, el esquema pasa a gestionarse con Flyway
-- (spring.jpa.hibernate.ddl-auto=validate) en vez de con la generación
-- automática de Hibernate.

create table users (
    is_active boolean,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    email varchar(255) not null unique,
    name varchar(255) not null,
    password_hash varchar(255) not null,
    primary key (id)
);

create table user_roles (
    user_id bigint not null,
    role varchar(255) check (role in ('ADMIN','EMPLOYEE'))
);

create table labels (
    is_active boolean not null,
    color varchar(7) not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    name varchar(100) not null unique,
    primary key (id)
);

create table tickets (
    assigned_to bigint,
    closed_at timestamp(6),
    created_at timestamp(6) not null,
    created_by bigint not null,
    id bigint generated by default as identity,
    updated_at timestamp(6),
    closing_message TEXT,
    description TEXT not null,
    email_subject varchar(255),
    priority varchar(255) not null check (priority in ('LOW','MEDIUM','HIGH','CRITICAL')),
    status varchar(255) not null check (status in ('OPEN','IN_PROGRESS','CLOSED')),
    title varchar(255) not null,
    primary key (id)
);

create table ticket_labels (
    label_id bigint not null,
    ticket_id bigint not null,
    primary key (label_id, ticket_id)
);

create table ticket_message (
    is_read boolean not null,
    author_id bigint,
    created_at timestamp(6),
    id bigint generated by default as identity,
    recipient_id bigint,
    ticket_id bigint not null,
    content TEXT not null,
    primary key (id)
);

create table activation_tokens (
    used boolean not null,
    code varchar(6) not null,
    created_at timestamp(6) not null,
    expires_at timestamp(6) not null,
    id bigint generated by default as identity,
    user_id bigint not null,
    type varchar(10) not null check (type in ('ACTIVATION','RESET')),
    primary key (id)
);

alter table if exists user_roles
    add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;

alter table if exists tickets
    add constraint FKmwsov8q6vll6krbx1co2ifp6t foreign key (assigned_to) references users;

alter table if exists tickets
    add constraint FKsytxppnwol0ckyehli7bqqbcr foreign key (created_by) references users;

alter table if exists ticket_labels
    add constraint FK8teehkwp8byltm3fwdcp4w28n foreign key (label_id) references labels;

alter table if exists ticket_labels
    add constraint FK5f747ty9jc8brq5516mu98s7c foreign key (ticket_id) references tickets;

alter table if exists ticket_message
    add constraint FK582kdfxrwwc1kxf6tremg7w6d foreign key (author_id) references users;

alter table if exists activation_tokens
    add constraint FKgtry5rof27b5hdur1a11y0gsn foreign key (user_id) references users;
